backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/images" # Media files will be stored in the repo under assets/images
public_folder: "../assets/images" # The src attribute for uploaded media will begin with /assets/images

collections:
  - name: "promotores"
    label: "Promotores / Distribuidores"
    files:
      - label: "Lista de Distribuidores"
        name: "lista"
        file: "promotores.json"
        format: "json"
        description: "Añade, edita o elimina los datos de tu equipo."
        fields:
          - label: "Distribuidores"
            name: "promotores"
            widget: "list"
            fields:
              - {label: "ID (Identificador en el Enlace Ej: jusa)", name: "id", widget: "string"}
              - {label: "Nombre para mostrar", name: "nombre", widget: "string"}
              - {label: "Usuario ORYGN", name: "orygnUsername", widget: "string"}
              - {label: "WhatsApp (con código de país)", name: "whatsapp", widget: "string"}
